### ISSUE TITLE
Non-default z_dim bug

### ISSUE THREAD

**Issue by dominikzietlow** [bethgelab/slow_disentanglement#1]
Hi guys!

Deviating from the z_dim default value of 10 leads to issues when plotting the latent distributions:
https://github.com/bethgelab/slow_disentanglement/blame/17c589a608f04534f48d2b9897fa2f33b7b34cfb/scripts/solver.py#L362

It's hard-coded there (both the value of 10 and the 5 in line 370).

Cheers

**Comment by lukas-schott** [comment]
fixed
